=== victor-aunon/VEMOD-Plotter/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="engine">
					<xs:complexType>
						<xs:attribute name="pistonDiameter" type="xs:float" use="required" />
						<xs:attribute name="crankRadius" type="xs:float" use="required" />
						<xs:attribute name="fuelPCI" type="xs:float" use="required" />
						<xs:attribute name="totalDisplacement" type="xs:float" use="required" />
						<xs:attribute name="cylinders" type="xs:unsignedByte" use="required" />
						<xs:attribute name="injectionPulses" type="xs:unsignedByte" use="required" />
					</xs:complexType>
				</xs:element>
				<xs:element name="plotStyles">
					<xs:complexType>
						<xs:attribute name="lineStyleExp" type="xs:string" use="optional" />
						<xs:attribute name="lineStyleModel" type="xs:string" use="optional" />
						<xs:attribute name="lineWidthExp" type="xs:float" use="optional" />
						<xs:attribute name="lineWidthModel" type="xs:float" use="optional" />
						<xs:attribute name="colorExp" type="xs:string" use="optional" />
						<xs:attribute name="colorModel" type="xs:string" use="optional" />
						<xs:attribute name="labelExp" type="xs:string" use="optional" />
						<xs:attribute name="labelModel" type="xs:string" use="optional" />
						<xs:attribute name="style" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="_classic_test"/>
									<xs:enumeration value="bmh"/>
									<xs:enumeration value="classic"/>
									<xs:enumeration value="dark_background"/>
									<xs:enumeration value="default"/>
									<xs:enumeration value="fast"/>
									<xs:enumeration value="fivethirtyeight"/>
									<xs:enumeration value="ggplot"/>
									<xs:enumeration value="grayscale"/>
									<xs:enumeration value="seaborn"/>
									<xs:enumeration value="seaborn-bright"/>
									<xs:enumeration value="seaborn-colorblind"/>
									<xs:enumeration value="seaborn-dark"/>
									<xs:enumeration value="seaborn-dark-palette"/>
									<xs:enumeration value="seaborn-darkgrid"/>
									<xs:enumeration value="seaborn-deep"/>
									<xs:enumeration value="seaborn-muted"/>
									<xs:enumeration value="seaborn-notebook"/>
									<xs:enumeration value="seaborn-paper"/>
									<xs:enumeration value="seaborn-pastel"/>
									<xs:enumeration value="seaborn-poster"/>
									<xs:enumeration value="seaborn-talk"/>
									<xs:enumeration value="seaborn-ticks"/>
									<xs:enumeration value="seaborn-white"/>
									<xs:enumeration value="seaborn-whitegrid"/>
									<xs:enumeration value="Solarize_Light2"/>
									<xs:enumeration value="tableau-colorblind10"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="fontSize" type="xs:unsignedByte" use="optional" />
						<xs:attribute name="fontFamily" type="xs:string" use="optional" />
						<xs:attribute name="font" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
				<xs:element name="plottingOptions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="emissions">
								<xs:complexType>
									<xs:attribute name="plot" type="xs:boolean" use="required" />
									<xs:attribute name="location" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="trends">
								<xs:complexType>
									<xs:attribute name="plot" type="xs:boolean" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="timeEvolution">
								<xs:complexType>
									<xs:attribute name="plot" type="xs:boolean" use="required" />
									<xs:attribute name="steadyVariablesFile" type="xs:string" use="optional" />
									<xs:attribute name="transientVariablesFile" type="xs:string" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="experimentalProcessing">
					<xs:complexType>
						<xs:sequence>
							<xs:element maxOccurs="unbounded" name="inputFile">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="category" use="required" >
												<xs:simpleType>
													<xs:restriction base="xs:string">
														<xs:enumeration value="calmecAverages"/>
														<xs:enumeration value="experimentalRaw"/>
													</xs:restriction>
												</xs:simpleType>
											</xs:attribute>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="outputFile" type="xs:string" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="simulationProcessing">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="settings">
								<xs:complexType>
									<xs:attribute name="roomTempConditions" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="warm"/>
												<xs:enumeration value="cold"/>
												<xs:enumeration value="ambient"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="modelNamePrefix" type="xs:string" use="required" />
									<xs:attribute name="xmlCase" type="xs:string" use="required" />
									<xs:attribute name="simulationMode" use="optional">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="testbench"/>
												<xs:enumeration value="N-T"/>
												<xs:enumeration value="N-mf"/>
												<xs:enumeration value="vehicle"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="simulationPath" type="xs:string" use="optional" />
									<xs:attribute name="processingPath" type="xs:string" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="transient">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="divisions" minOccurs="0" maxOccurs="1" >
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="division">
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" use="required" />
															<xs:attribute name="start" type="xs:float" use="required" />
															<xs:attribute name="end" type="xs:float" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="errorEvaluation" minOccurs="0" maxOccurs="1" >
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="error">
														<xs:complexType>
															<xs:attribute name="pointsPercentage" type="xs:float" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="experimentalPath" type="xs:string" use="required" />
									<xs:attribute name="variablesFile" type="xs:string" use="required" />
									<xs:attribute name="simTime" type="xs:unsignedInt" use="optional" />
								</xs:complexType>
							</xs:element>
							<xs:element name="steady">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="cases">
											<xs:complexType>
												<xs:sequence>
													<xs:element maxOccurs="unbounded" name="case">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="nomenclature">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element minOccurs="1" maxOccurs="unbounded" name="labelPart">
																				<xs:complexType>
																					<xs:attribute name="property" use="required">
																						<xs:simpleType>
																							<xs:restriction base="xs:string">
																								<xs:enumeration value="speed"/>
																								<xs:enumeration value="load"/>
																								<xs:enumeration value="torque"/>
																								<xs:enumeration value="roomTemperature"/>
																								<xs:enumeration value="repetition"/>
																								<xs:enumeration value="date"/>
																								<xs:enumeration value="BMEP"/>
																								<xs:enumeration value="EGR"/>
																								<xs:enumeration value="undefined"/>
																							</xs:restriction>
																						</xs:simpleType>
																					</xs:attribute>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="name" type="xs:string" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="averagingPercentage" type="xs:unsignedByte" use="optional" />
									<xs:attribute name="experimentalFile" type="xs:string" use="required" />
									<xs:attribute name="variablesAverageFile" type="xs:string" use="required" />
									<xs:attribute name="variablesInstantaneousFile" type="xs:string" use="required" />
									<xs:attribute name="calmecInstantaneousPath" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== victor-aunon/VEMOD-Plotter/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
    <engine pistonDiameter="0.08002" crankRadius="0.0398" fuelPCI="42.92" totalDisplacement="0.0016" cylinders="4" 
        injectionPulses="3"/>
    <plotStyles lineStyleExp="-" lineStyleModel=":" lineWidthExp="1.5" lineWidthModel="1.5" colorExp="#E24A33" colorModel="#348ABD"
        labelExp="Reference" labelModel="VEMOD" style="ggplot" fontSize="14" fontFamily="sans-serif" font="DejaVu Sans" />
    <plottingOptions>
        <emissions plot="true" location="Pipe/Exhaust/0.010m" />
        <trends plot="true" />
        <timeEvolution plot="true" steadyVariablesFile="Steady_model_vars.dat"
            transientVariablesFile="Transient_model_vars.dat" />
    </plottingOptions>
    <experimentalProcessing>
        <inputFile category="calmecAverages">
           D:/UPV/Jaime Martín Díaz - 0_VEMOD_OneDrive/1_Ensayos/0_Ensayos_sala_12/Estacionarios/Resglob_20180926.dat
        </inputFile>
        <inputFile category="experimentalRaw">
            D:/UPV/Jaime Martín Díaz - 0_VEMOD_OneDrive/1_Ensayos/0_Ensayos_sala_12/Estacionarios/TodasCombustiones.xlsx
        </inputFile>
        <outputFile>
            ../INPUT_dataset/medidas_SS/ExperimentalData.xlsx
        </outputFile>
    </experimentalProcessing>
    <simulationProcessing>
        <settings roomTempConditions="ambient" modelNamePrefix="R9M_lab12_" xmlCase="Default" simulationMode="testbench"
            simulationPath="../User_VEMOD_Model/simulation/results" processingPath="" />
        <transient experimentalPath="../INPUT_dataset/medidas_WLTC" variablesFile="Variables_transient.dat" simTime="1800">
            <divisions>
                <division name="Low" start="0.0" end="589" />
                <division name="Medium" start="589" end="1022" />
                <division name="High" start="1022" end="1477" />
                <division name="Extra High" start="1477" end="1800" />
            </divisions>
            <errorEvaluation>
                <error pointsPercentage="50" />
                <error pointsPercentage="70" />
                <error pointsPercentage="80" />
                <error pointsPercentage="90" />
                <error pointsPercentage="95" />
            </errorEvaluation>
        </transient>
        <steady averagingPercentage="3" experimentalFile="../INPUT_dataset/medidas_SS/ExperimentalData.xlsx" 
            variablesAverageFile="Variables_avg.dat" variablesInstantaneousFile="Variables_ins.dat" 
            calmecInstantaneousPath="D:/UPV/Jaime Martín Díaz - 0_VEMOD_OneDrive/1_Ensayos/0_Ensayos_sala_12/Estacionarios/Instantaneous_20180926" >
            <cases>
                <case name="0850_000_h_2">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1000_021_h_2">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1000_044_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1000_066_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1000_088_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1250_013_h_6">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1250_026_h_4">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1250_050_h_6">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1250_076_h_5">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1250_100_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1500_011_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1500_025_h_2">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1500_050_h_3">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1500_075_h_2">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="1500_100_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="2500_025_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="2500_050_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="2500_075_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="2500_100_h_3">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
                        <labelPart property="repetition"/>
                    </nomenclature>
                </case>
                <case name="3500_025_h_1">
                    <nomenclature>
                        <labelPart property="speed"/>
                        <labelPart property="load"/>
                        <labelPart property="roomTemperature"/>
